갤럭시 사용자 데이터 분석  
디지털 기기 취급 전문업체 A는 오프라인 매장에서 갤럭시 제품군을 구매한 이력이 있는 사람들의 단말기 이용 형태를 분석하기 위해 통신사 MT로부터 익명화 처리된 고객 정보를 일부 구매하였다. 해당 데이터에서 인사이트를 뽑기위해 다양한 분석을 해보고자 한다.  

데이터: galaxy_users.csv  ( 7032 rows, 21 columns, UTF-8)  

customer_ID, string, 고객 식별자  
gender, string, 성별  
SeniorCitizen, int, 시니어 여부(1: 시니어, 0:아님)  
Parner, string, 배우자 존재여부 (Yes: 있음, No:없음)  
Dependents, string, 부양가족 (Yes있음, No 없음)  
tenure, int, 현 직장 근속 월수  
PhoneService, string, 단말 서비스 사용여부 (Yes사용 중, No 해지)  
MultipleLines, string, 다중회선개통여부 (Yes, 사용중, No 미사용)  
InternetService, string, 인터넷 사용  (DSL 저속 서비스, Fiber optic 고속 서비스, No 미사용)  
OnlineSecurity, string, 온라인보안서비스 사용 (Yes, No)  
OnlineBackup, string, 온라인 백업 서비스 (Yes, No)   
DeviceProtection, string, 기기보호 서비스 (Yes, No)  
TechSupport, string, 기술지원서비스 (Yes, No)  
StreamingTV, string, 스트리밍 지원 TV  
StreamingMovies, string, 영화 스트리밍 서비스  
Contract, string, 계약 갱신 주기  
PaperlessBiling, string, 온라인 명세서 발급 서비스 (Yes, No)  
PaymentMethod, string,  납부방법  
MonthlyCharges, float, 월별청구금액  
TotalCharges, float, 누적청구금액  
Churn, string, 이탈여부 (yes 이탈, no 잔존)  

필요 라이브러리 및 클래스 목록  
from sklearn.preprocessing import MinMaxScaler  
from sklearn.model_selection import train_test_split  
from sklearn.linear_model import LogisticRegression  
from sklearn.metrics import f1_score  

문제1. 부가 서비스를 많이 사용할수록 제품 또는 브랜드에 고관여되어 있다는 가설ㅇ르 세우고 분석을 하고자 한다. 이에 앞서 고객별 부가서비스 사용현황통계를 산출하고자 한다. 부가 서비스를 1개 사용하는 사람은 부가 서비스를 6개 사용하는 사람보다 몇 배나 많은지 계산하시오.  
. 부가서비스 대상변수: OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies  
. 부가서비스 변수의 범주가 Yes인경우 1로, No인 경우 0으로 간주한다.  
. 부가 서비스 변수에 yes 또는 No가 아닌 다른 범주가 있는 경우 해당 행은 제거 후 분석하시오.  
. 첫 번째 고객(7590-VHVEG)의 경우, 부가서비스는 1개 이용중이다.  
. 정답은 반올림하여 소수점 1째 자리까지 출력하시오

문제2. 여러 변수간 상관관계를 확인하고자 한다. 현 직장 근속월수(tenure), 월별 청구금액(MonthlyCharges), 통신사 사용월수간 피어슨 상관분석을 실시하고 그 결과 중 상관계수 절대값이 가장 높은 것을 확인하시오.  
. 통신사 사용월수는 총 청구긍액(TotalCharges)을 월별청구금액(MonthlyCharges)로 나눈 값의 몫으로 한다.  
. 본 ㅁ누제풀이에 계약생신주기( contract)는 관련없음.  
. 정답은 반올림하여 소수점 3째자리까지 출력하시오.

문제3. 고객이탈여부(Churn)을 종속변수로 하는 모델을 만들어보고자 한다. 데이터 모델 분할 후 정규화를 실시하여 로지스특 회귀분석을 실시하고 해당 모델을 기준점 삼아 모델을 개선하고자 한다. 주어진 독립변수를 활용하여 F1-score로 모델을 평가하시오.  

<독립변수>  
- 시니어 여부 - 파트너 존재여부 - 부양가족 존재여부 - 현직장 근속개월수 - 월별 청구금액 - 누적 청구금액, -온라인 보안 서비스, - 온라인 백업서비스, - 기기보호 서비스, - 기술지원서비스, - 영화 스트리밍 서비스, - 온라인 명세서 발급 서비스  
<종속변수>  
- 고객이탈여부  

. 범주형 변수의 범주가 Yes인 경우 1로 , No인 경우 0으로 치환하여 분석하시오.  
. 범주형 변수에서 yes와 No가 아닌 나머지 범주는 -1로 치환하시오.  
. 학습 및 평가 데이터 세트 분할비는 7:3  
. 정규화는 Min-Max정규화를 실시하여 모든 변수를 대상으로 하시오  
. 평가데이터 세트는 학습데이터 세트기반으로 정규화 하시오.  
. seed는 123으로 고정하시오.  
. 정답은 소수점 2째자리까지 출력하시오

난이도 조절방법  
1. 잘 사용하지 않는 전처리 사용하게  
2. 필터링 단계를 여러번으로  

In [1]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

In [2]:
df = pd.read_csv("galaxy_users.csv")
df.head(2)

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0  7590-VHVEG  Female              0     Yes         No       1           No   
1  5575-GNVDE    Male              0      No         No      34          Yes   

      MultipleLines InternetService OnlineSecurity  ... DeviceProtection  \
0  No phone service             DSL             No  ...               No   
1                No             DSL            Yes  ...              Yes   

  TechSupport StreamingTV StreamingMovies        Contract PaperlessBilling  \
0          No          No              No  Month-to-month              Yes   
1          No          No              No        One year               No   

      PaymentMethod MonthlyCharges  TotalCharges  Churn  
0  Electronic check          29.85         29.85     No  
1      Mailed check          56.95       1889.50     No  

[2 rows x 21 columns]

In [3]:
# df.iloc[0, ]

In [4]:
df.iloc[0:2, ].transpose()

0             1
customerID              7590-VHVEG    5575-GNVDE
gender                      Female          Male
SeniorCitizen                    0             0
Partner                        Yes            No
Dependents                      No            No
tenure                           1            34
PhoneService                    No           Yes
MultipleLines     No phone service            No
InternetService                DSL           DSL
OnlineSecurity                  No           Yes
OnlineBackup                   Yes            No
DeviceProtection                No           Yes
TechSupport                     No            No
StreamingTV                     No            No
StreamingMovies                 No            No
Contract            Month-to-month      One year
PaperlessBilling               Yes            No
PaymentMethod     Electronic check  Mailed check
MonthlyCharges               29.85         56.95
TotalCharges                 29.85        1889.5
Churn                           No            No

### Q1.

In [5]:
df_q1 = df.loc[:, "OnlineSecurity":"StreamingMovies"].copy()
df_q1.head(2)

OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0             No          Yes               No          No          No   
1            Yes           No              Yes          No          No   

  StreamingMovies  
0              No  
1              No

In [6]:
df_q1 = df_q1.replace({"Yes": 1, "No": 0})
df_q1.head(2)

OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0              0            1                0           0           0   
1              1            0                1           0           0   

  StreamingMovies  
0               0  
1               0

In [7]:
df_q1["OnlineSecurity"].unique()

array([0, 1, 'No internet service'], dtype=object)

In [8]:
for n_col in df_q1.columns:
    print(n_col, df_q1[n_col].unique())

OnlineSecurity [0 1 'No internet service']
OnlineBackup [1 0 'No internet service']
DeviceProtection [0 1 'No internet service']
TechSupport [0 1 'No internet service']
StreamingTV [0 1 'No internet service']
StreamingMovies [0 1 'No internet service']


In [9]:
# df_q1.unique()
# df_q1.drop_duplicates() # row 중복 제거....이나 여기서는 적절하지 않음.
df_q1.apply(lambda x: [x.unique()]) # 시험버전
df_q1.apply(lambda x: x.unique()) # 최신버전

OnlineSecurity         OnlineBackup     DeviceProtection  \
0                    0                    1                    0   
1                    1                    0                    1   
2  No internet service  No internet service  No internet service   

           TechSupport          StreamingTV      StreamingMovies  
0                    0                    0                    0  
1                    1                    1                    1  
2  No internet service  No internet service  No internet service

In [10]:
df_q1_sub = df_q1.loc[df_q1["OnlineSecurity"] != "No internet service", ]
df_q1_sub.apply(lambda x: x.unique())
# 앗?? 왜지!?!?

OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingTV  \
0              0            1                0           0           0   
1              1            0                1           1           1   

  StreamingMovies  
0               0  
1               1

In [11]:
df_q1.loc[df_q1["OnlineSecurity"] == "No internet service", ].head()

OnlineSecurity         OnlineBackup     DeviceProtection  \
11  No internet service  No internet service  No internet service   
16  No internet service  No internet service  No internet service   
21  No internet service  No internet service  No internet service   
22  No internet service  No internet service  No internet service   
33  No internet service  No internet service  No internet service   

            TechSupport          StreamingTV      StreamingMovies  
11  No internet service  No internet service  No internet service  
16  No internet service  No internet service  No internet service  
21  No internet service  No internet service  No internet service  
22  No internet service  No internet service  No internet service  
33  No internet service  No internet service  No internet service

#### "No internet service"가 중구난방으로 위치한 경우 효과적으로 제거하는 방법.
※ 단, 처리 대상 객체에 결측치가 없어야 한다.

In [12]:
df_q1_sub = df_q1.replace("No internet service", np.nan).dropna()
df_q1_sub.apply(lambda x: x.unique())

OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
0             0.0           1.0               0.0          0.0          0.0   
1             1.0           0.0               1.0          1.0          1.0   

   StreamingMovies  
0              0.0  
1              1.0

In [13]:
df_q1_sub["cnt"] = df_q1_sub.sum(axis = 1)
df_q1_sub.head(2)

OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  StreamingTV  \
0             0.0           1.0               0.0          0.0          0.0   
1             1.0           0.0               1.0          0.0          0.0   

   StreamingMovies  cnt  
0              0.0  1.0  
1              0.0  2.0

In [14]:
ser_cnt = df_q1_sub["cnt"].value_counts()
ser_cnt

cnt
3.0    1117
2.0    1033
1.0     966
4.0     850
0.0     693
5.0     569
6.0     284
Name: count, dtype: int64

In [15]:
round(ser_cnt[1] / ser_cnt[6], 1)

3.4

### Q2.

In [16]:
df_q2 = df[["tenure", "MonthlyCharges", "TotalCharges"]].copy()
df_q2.head(2)

tenure  MonthlyCharges  TotalCharges
0       1           29.85         29.85
1      34           56.95       1889.50

In [17]:
5 // 2

2

In [18]:
df_q2["month"] = df_q2["TotalCharges"] // df_q2["MonthlyCharges"]
df_q2.head(2)

tenure  MonthlyCharges  TotalCharges  month
0       1           29.85         29.85    1.0
1      34           56.95       1889.50   33.0

In [19]:
df_q2.iloc[:, [0, 1, 3]].corr().round(3) # 0.999

tenure  MonthlyCharges  month
tenure           1.000           0.247  0.999
MonthlyCharges   0.247           1.000  0.246
month            0.999           0.246  1.000

### Q3.

In [20]:
col1 = ["SeniorCitizen", "Partner", "Dependents", "tenure", "MonthlyCharges", "TotalCharges"]
col2 = ["OnlineSecurity", "OnlineBackup", "DeviceProtection", "TechSupport", "StreamingMovies", "PaperlessBilling"]
df_q3 = df[["Churn"] + col1 + col2].copy()
df_q3.head(2)

Churn  SeniorCitizen Partner Dependents  tenure  MonthlyCharges  \
0    No              0     Yes         No       1           29.85   
1    No              0      No         No      34           56.95   

   TotalCharges OnlineSecurity OnlineBackup DeviceProtection TechSupport  \
0         29.85             No          Yes               No          No   
1       1889.50            Yes           No              Yes          No   

  StreamingMovies PaperlessBilling  
0              No              Yes  
1              No               No

In [21]:
df_q3 = df_q3.replace({"Yes": 1, "No": 0})
df_q3.head(2)

Churn  SeniorCitizen  Partner  Dependents  tenure  MonthlyCharges  \
0      0              0        1           0       1           29.85   
1      0              0        0           0      34           56.95   

   TotalCharges OnlineSecurity OnlineBackup DeviceProtection TechSupport  \
0         29.85              0            1                0           0   
1       1889.50              1            0                1           0   

  StreamingMovies  PaperlessBilling  
0               0                 1  
1               0                 0

In [22]:
df_q3.dtypes

Churn                 int64
SeniorCitizen         int64
Partner               int64
Dependents            int64
tenure                int64
MonthlyCharges      float64
TotalCharges        float64
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingMovies      object
PaperlessBilling      int64
dtype: object

In [23]:
# 시험버전 Pandas에서 구현은 되어있으나 버그로 동작안함
df_q3_obj = df_q3.select_dtypes(exclude = "number")
df_q3_obj.head(1)

OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingMovies
0              0            1                0           0               0

In [24]:
ser_dtypes = df_q3.dtypes
ser_dtypes[ser_dtypes == "object"].index.to_list()

['OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingMovies']

In [25]:
df_q3_obj = df_q3[ser_dtypes[ser_dtypes == "object"].index.to_list()]
df_q3_obj.head(1)

OnlineSecurity OnlineBackup DeviceProtection TechSupport StreamingMovies
0              0            1                0           0               0

In [26]:
df_q3_obj.apply(lambda x: x.unique())

OnlineSecurity         OnlineBackup     DeviceProtection  \
0                    0                    1                    0   
1                    1                    0                    1   
2  No internet service  No internet service  No internet service   

           TechSupport      StreamingMovies  
0                    0                    0  
1                    1                    1  
2  No internet service  No internet service

In [27]:
df_q3 = df_q3.replace({"No internet service": -1})
df_q3.head(2)

Churn  SeniorCitizen  Partner  Dependents  tenure  MonthlyCharges  \
0      0              0        1           0       1           29.85   
1      0              0        0           0      34           56.95   

   TotalCharges  OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
0         29.85               0             1                 0            0   
1       1889.50               1             0                 1            0   

   StreamingMovies  PaperlessBilling  
0                0                 1  
1                0                 0

In [28]:
df_train, df_test = train_test_split(df_q3, train_size = 0.7, random_state = 123)
len(df_train), len(df_test)

(4922, 2110)

In [29]:
model_nor = MinMaxScaler().fit(df_train)
arr_train_nor = model_nor.transform(df_train)
arr_test_nor  = model_nor.transform(df_test)

In [30]:
arr_train_nor[:1, ]

array([[1.        , 0.        , 0.        , 0.        , 0.08450704,
        0.81116094, 0.07551927, 0.5       , 1.        , 0.5       ,
        0.5       , 1.        , 1.        ]])

In [31]:
df_train_nor = pd.DataFrame(arr_train_nor, columns = df_train.columns)
df_train_nor.head(1)

Churn  SeniorCitizen  Partner  Dependents    tenure  MonthlyCharges  \
0    1.0            0.0      0.0         0.0  0.084507        0.811161   

   TotalCharges  OnlineSecurity  OnlineBackup  DeviceProtection  TechSupport  \
0      0.075519             0.5           1.0               0.5          0.5   

   StreamingMovies  PaperlessBilling  
0              1.0               1.0

In [32]:
model_nor.data_max_

array([1.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 7.2000e+01,
       1.1875e+02, 8.6848e+03, 1.0000e+00, 1.0000e+00, 1.0000e+00,
       1.0000e+00, 1.0000e+00, 1.0000e+00])

In [33]:
model_nor.data_min_

array([ 0. ,  0. ,  0. ,  0. ,  1. , 18.4, 18.8, -1. , -1. , -1. , -1. ,
       -1. ,  0. ])

In [34]:
model_lr = LogisticRegression(random_state = 123)
model_lr.fit(X = arr_train_nor[:, 1:], 
             y = arr_train_nor[:, 0 ])
pred = model_lr.predict(arr_test_nor[:, 1:])
pred[:4]

array([0., 0., 0., 0.])

In [35]:
round(f1_score(y_true = arr_test_nor[:, 0],
               y_pred = pred), 2)

0.55

#### Q. 특정 범주를 제외한 나머지를 특정 값으로 바꿔야 한다면?
※ E와 H를 제외한 나머지 범주를 모두 -1로 치환하시오.

In [37]:
df_dia = pd.read_csv("../diamonds.csv")
df_dia.head(2)

carat      cut color clarity  depth  table  price     x     y     z
0   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31

In [46]:
# 시험버전
# ser_u = df_dia.iloc[:, 1:4].apply(lambda x: [x.unique()]).explode().explode()
# ser_u

In [47]:
ser_u = df_dia.iloc[:, 1:4].apply(lambda x: x.unique()).explode()

In [48]:
np.where(ser_u.isin(["E", "H"]), ser_u, -1)

array([-1, -1, -1, -1, -1, 'E', -1, -1, 'H', -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1], dtype=object)

In [50]:
ser_repl = pd.Series(np.where(ser_u.isin(["E", "H"]), ser_u, -1), 
                     index = ser_u)
ser_repl.to_dict()

{'Ideal': -1,
 'Premium': -1,
 'Good': -1,
 'Very Good': -1,
 'Fair': -1,
 'E': 'E',
 'I': -1,
 'J': -1,
 'H': 'H',
 'F': -1,
 'G': -1,
 'D': -1,
 'SI2': -1,
 'SI1': -1,
 'VS1': -1,
 'VS2': -1,
 'VVS2': -1,
 'VVS1': -1,
 'I1': -1,
 'IF': -1}

In [51]:
df_dia2 = df_dia.replace(ser_repl) # .replace() 메서드에는 series 객체도 넣을 수 있다.
df_dia2.iloc[:, 1:4].apply(lambda x: x.unique())

cut              [-1]
color      [E, -1, H]
clarity          [-1]
dtype: object

In [36]:
ser = pd.Series([1, 3, 5])
ser.map(lambda x: x + 100)

0    101
1    103
2    105
dtype: int64